del D:\lazarus-signal-light-v2\Signal-light.exe
rename D:\lazarus-signal-light-v2\Project1.exe Signal-light.exe
del D:\lazarus-signal-light-v2\Signal-Light-Release\Signal-light.exe
del D:\lazarus-signal-light-v2\Signal-Light-Release Admin\Signal-light.exe
copy D:\lazarus-signal-light-v2\Signal-light.exe D:\lazarus-signal-light-v2\Signal-Light-Release\
copy D:\lazarus-signal-light-v2\Signal-light.exe D:\lazarus-signal-light-v2\Signal-Light-Release-Admin\